### PR TITLE
Use stern/stern

### PR DESCRIPTION
**Pull request by superbrothers**
This PR changes to use https://github.com/stern/stern instead of https://github.com/wercker/stern.

wercker/stern is no longer active repository. Currently, volunteer maintainers have started maintenance stern on stern/stern repository.

## REF

- https://github.com/wercker/stern/issues/140

### CODE REVIEW

**Comment by superbrothers** [comment]
Umm... It works on my local environment, but test failed :thinking:

```
$ shellcheck -V
ShellCheck - shell script analysis tool
version: 0.7.1
license: GNU General Public License, version 3
website: https://www.shellcheck.net
$ shellcheck bin/*
$ git show --quiet
commit 9bf952bf6aa12b3cfafec541ade278ca4467b026 (HEAD -> stern/stern, superbrothers/stern/stern)
Author: Kazuki Suda <kazuki.suda@gmail.com>
Date:   Wed Oct 28 09:30:12 2020 +0900

    Use stern/stern
$ asdf plugin-add stern ./
$ asdf list-all stern
1.12.0
1.12.1
$ asdf install stern 1.12.1
Creating bin directory
Downloading [stern] from https://github.com/stern/stern/releases/download/v1.12.1/stern_1.12.1_darwin_amd64.tar.gz to /var/folders/d3/lsp0h4wx7wsd4_yrymm9nnm80000gn/T/asdf_ZxXkbMMF/stern_1.12.1_darwin_amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   658  100   658    0     0    862      0 --:--:-- --:--:-- --:--:--   861
100 8380k  100 8380k    0     0  1948k      0  0:00:04  0:00:04 --:--:-- 3169k
Cleaning previous binaries
Extracting archive file
Copying binary
$ asdf which stern 1.12.1
/Users/ksuda/.asdf/installs/stern/1.12.1/bin/stern
$ /Users/ksuda/.asdf/installs/stern/1.12.1/bin/stern --version
stern version 1.12.1
```

**Comment by superbrothers** [comment]
ping @looztra

**Comment by looztra** [comment]
I already faced the same problem and that's why I moved some of my asdf plugins to use github actions, like https://github.com/looztra/asdf-bottom for instance.

Could you add the move from travis to github action in your PR?
If you don't want to, I'll provide it and you will be able to rebase on the changed `master`

**Comment by superbrothers** [comment]
@looztra I've created a commit to use GitHub Actions instead of Travis CI.

**Comment by looztra** [comment]
Thank you!

Could you please : 

- change the lint config to something like : 

```yaml
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Shellcheck
      run: |
        which shellcheck
        shellcheck -V
        shellcheck bin/*
```

- remove the `.travis.ci` file
- remove the `shellcheck-on-linux-only.sh` file as it is not needed anymore (shellcheck is available by default on linux and macos runners)

(I've experimted these modifications in https://github.com/looztra/asdf-stern/pull/4/files but I'll merge your PR and close mine afterwards)

**Comment by superbrothers** [comment]
It seems that shellcheck is not installed on macos-latest. I'll change it to run the lint job on ubunut-latest only.

**Comment by superbrothers** [comment]
I've updated it. Could you review the changes?

**Comment by looztra** [comment]
You're right, my bad, I was not using the strategy in my PR for the lint part.
That's not a big deal, we don't need to run shellcheck on each os after all.

Thanks a lot!

**Pull request merged**
